name: Smoke

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  smoke:
    strategy:
      matrix:
        runner:
          - macos-15
          - ubuntu-24.04
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - run: nix build
      - run: result/bin/cabal-gild --version
